services:


  vitrin-test:
    build: .
    container_name: vitrin-test
    ports:
      - 8000:80
    environment:
      - TITLE="Help!"
      - AUTOINDEX=on
      - DOWNLOAD_PATH=/a/b/c/d/
    volumes:
      - /var/www/html/test/:/download/

